### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.jmock.lib.legacy.ClassImposteriser$3

### ISSUE THREAD

**Issue by Coheris** [jmock-developers/jmock-library#156]
Using Maven 1.6.2 (and surefire plugin 3.0.0-M3) and jmock-legacy 2.12.0 and java 11, I get a lot of test failures with the message "java.lang.NoClassDefFoundError: Could not initialize class org.jmock.lib.legacy.ClassImposteriser$3".  In the "boot classpath" displayed by maven (for the command "mvn test -X"), I can see that the jmock jars are present : (...\.m2\repository\org\jmock\jmock\2.12.0\jmock-2.12.0.jar  ...\.m2\repository\org\jmock\jmock-testjar\2.12.0\jmock-testjar-2.12.0.jar ...\.m2\repository\org\jmock\jmock-legacy\2.12.0\jmock-legacy-2.12.0.jar).
There is an error (ava.lang.IllegalArgumentException) which precedes the first NoClassDefFoundError, which is triggered by the following line of code :
final ResultSet rs = this.context.mock(ResultSet.class);
For info, context is defined as:
	private final Mockery context = new Mockery() {{
	      this.setImposteriser(ClassImposteriser.INSTANCE);
	}};
Is this a maven issue or maybe a problem with cglib and java 11?

**Comment by Coheris** [comment]
Abbreviated stack trace : 
java.lang.ExceptionInInitializerError
	at org.jmock.lib.legacy.ClassImposteriser.proxyClass(ClassImposteriser.java:100)
	at org.jmock.lib.legacy.ClassImposteriser.imposterise(ClassImposteriser.java:69)
	at org.jmock.Mockery.mock(Mockery.java:167)
	at org.jmock.Mockery.mock(Mockery.java:143)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:78)
	at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49)
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)

I don't know why java.sql.ResultSet.class would cause a problem with asm.

**Comment by Coheris** [comment]
Problem solved - there were 2 different versions of asm on my classpath because of transitive dependencies.  It seems that Apache Tika 1.10 does not mix well with jmock 2.12.0.
