### ISSUE TITLE
Mocking some Java classes with ClassImposteriser in Java 8 causes IllegalArgumentException

### ISSUE THREAD

**Issue by jflecomte** [jmock-developers/jmock-library#79]
If I try to mock a java.io.File using the ClassImposteriser, I get the following stack trace:

```
java.lang.IllegalArgumentException: null
        at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
        at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
        at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
        at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
        at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
        at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
        at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
        at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
        at org.jmock.lib.legacy.ClassImposteriser.proxyClass(ClassImposteriser.java:121)
        at org.jmock.lib.legacy.ClassImposteriser.imposterise(ClassImposteriser.java:66)
        at org.jmock.Mockery.mock(Mockery.java:148)
        at org.jmock.Mockery.mock(Mockery.java:124)
        at MockTest.testMock(MockTest.java:21)
```

I'm using:
Java 1.8.0_40
JUnit 4.12
JMock 2.8.1

Trying to mock a java.util.Date does the same.
If I use Java 1.7, it is OK.
If I use JMock 2.6.0, it is OK.

My test is:

```java
import java.io.File;

import org.jmock.integration.junit4.JUnitRuleMockery;
import org.jmock.lib.legacy.ClassImposteriser;
import org.junit.Rule;
import org.junit.Test;

public class MockTest
{
    @Rule
    public final JUnitRuleMockery _context = new JUnitRuleMockery()
    {
        {
            setImposteriser(ClassImposteriser.INSTANCE);
        }
    };

    @Test
    public void testMock()
    {
        _context.mock(File.class);
    }
}
```

My pom.xml is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <version>1.00-SNAPSHOT</version>
    <groupId>test</groupId>
    <artifactId>my-project</artifactId>
    <packaging>jar</packaging>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.3</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.18.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
                
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            
        </plugins> 

    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.12</version>
            </dependency>
            <dependency>
                <groupId>org.jmock</groupId>
                <artifactId>jmock</artifactId>
                <version>2.8.1</version>
            </dependency>
            <dependency>
                <groupId>org.jmock</groupId>
                <artifactId>jmock-junit4</artifactId>
                <version>2.8.1</version>
            </dependency>
            <dependency>
                <groupId>org.jmock</groupId>
                <artifactId>jmock-legacy</artifactId>
                <version>2.8.1</version>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-core</artifactId>
                <version>1.3</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmock</groupId>
            <artifactId>jmock</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmock</groupId>
            <artifactId>jmock-junit4</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jmock</groupId>
            <artifactId>jmock-legacy</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
  

</project>
```

**Comment by sf105** [comment]
Firstly, don’t mock Date. It’s a value type that you can just set.

We also recommend not mocking library types, like File. Normally, we would have a domain type to represent how we use the file and mock that. For the actual use of the File, we might write integration tests. We’ve written this up in the Growing Object Oriented Software book.

S

**Comment by jflecomte** [comment]
I agree for the Date. Usually I avoid mocking objects anyway. But right now I was just trying to figure out why 50+ unit tests suddenly failed in my current project just because I upgraded from jmock 2.6.0 to 2.8.1... Date is never actually being mocked in my project, but some methods returning Date are being mocked and they fail with the same exception. 

For example:

```Java
    @Test
    public void testReturnDate()
    {
        final DateGetter mockDateGetter = _context.mock(DateGetter.class);

        _context.checking(new Expectations()
        {
            {
                oneOf(mockDateGetter).getDate();
                will(returnValue(new Date()));
            }
        });

        mockDateGetter.getDate();
    }

    private static interface DateGetter
    {
        Date getDate();
    }
```
Fortunately in many cases in my current project I can use the default Imposteriser instead of the ClassImposteriser since no Object is being mocked in the test, but in many cases I can't (without refactoring many classes to extract interfaces).

Anyway, this behaviour seemed to me like a regression from 2.6.0. I know that the ClassImposteriser has been in the "legacy" package for a while. Does that mean it will no longer be supported?

Thanks

**Comment by olibye** [comment]
Thanks for the example code, I'll have a look.

**Comment by wimdeblauwe** [comment]
I am having the same issue using Java 8 with JMock 2.8.1. I am guessing it is related to http://stackoverflow.com/questions/27092857/cglib-throws-an-illegalargumentexception-when-enhancing-the-java-util-date-class

**Comment by npryce** [comment]
'I know that the ClassImposteriser has been in the "legacy" package for a while. Does that mean it will no longer be supported?'

The legacy package is classes for working with legacy code rather than new code.

**Comment by ericslandry** [comment]
Same for me. Does cglib 3.2 fix this?
https://github.com/cglib/cglib/issues/20

**Comment by olibye** [comment]
Thanks, I'll look in to that

**Comment by ericslandry** [comment]
After fighting with Ivy, I tested it and cglib 3.2 fixes my problem

**Comment by olibye** [comment]
Thanks, do you want to submit a pull request for updated dependencies for
jmock?
