### ISSUE TITLE
IncompatibleClassChangeError after upgrade to jmock 2.8.3

### ISSUE THREAD

**Issue by msymons** [jmock-developers/jmock-library#97]
JMock v2.8.2 release notes report "Upgrade cglib and asm for the ClassImposteriser to support Java8."

Following upgrade from JMock v2.8.1 to v2.8.3, and with no other changes, every one of our JMock tests is now breaking for a job using:

Jenkins v2.46.2
Maven 3.2.3
jdk1.7.0_97

```
java.lang.IncompatibleClassChangeError: class net.sf.cglib.core.DebuggingClassWriter has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:231)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:149)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:117)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:109)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:105)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:71)
	at org.jmock.lib.legacy.ClassImposteriser.proxyClass(ClassImposteriser.java:97)
	at org.jmock.lib.legacy.ClassImposteriser.imposterise(ClassImposteriser.java:66)
	at org.jmock.Mockery.mock(Mockery.java:148)
	at org.jmock.auto.internal.Mockomatic.autoMock(Mockomatic.java:38)
	at org.jmock.auto.internal.Mockomatic.fillIn(Mockomatic.java:28)
	at org.jmock.integration.junit4.JUnitRuleMockery$1.fillInAutoMocks(JUnitRuleMockery.java:72)
	at org.jmock.integration.junit4.JUnitRuleMockery$1.prepare(JUnitRuleMockery.java:55)
	at org.jmock.integration.junit4.JUnitRuleMockery$1.evaluate(JUnitRuleMockery.java:47)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Testing with latest versions of cglib and asm did not help.
Rolling back to JMock v2.8.1 solves the problem. 

Thoughts?

**Comment by olibye** [comment]
org.objectweb.asm.ClassVisitor changed from an interface in asm-3.X.X to a Class in asm-5.X.X

Something else in your pom is pulling in an old version of asm.
`mvn dependency:tree`
Will tell you how each version of each transitive dependency is pulled in.

Then either
- remove it if it's explicit.
- upgrade the dependency to pull in a new version.

Or I could make a shaded 'nodeps' build of jmock that shades the jmock dependencies into another name space.

**Comment by olibye** [comment]
@msymons can I close this?

For newer versions of jmock I'm considering shading the dependencies so that this class of problem goes away. Do you think that would be useful?

**Comment by msymons** [comment]
Yes, @olibye ,  I think it would be useful - so this issue can be closed.

Per your 2017 comment, shading the dependencies was something that you offered to do in a special build (and I apologise for not replying at the time).

Once the new version of jmock is available then It'll be fairly easy for me to test and then give feedback.
